import React, { Component } from "react";

class PrivacyPolicy extends Component {
  render() {
    return (
      <div>
        <h2>Privacy Policy</h2>
        <p>Your privacy is critically important to us.</p>
        <address>
          Deni Hidayat<br />Bandung Bandung, Bandung <br />40383 - Jawa Barat , Indonesia<br />085721661555			</address>
        <p>It is Deni Hidayat's policy to respect your privacy regarding any information we may collect while operating our website. This Privacy Policy applies to <a href="https://denihida1216.github.io">https://denihida1216.github.io</a> (hereinafter, "us", "we", or "https://denihida1216.github.io"). We respect your privacy and are committed to protecting personally identifiable information you may provide us through the Website. We have adopted this privacy policy ("Privacy Policy") to explain what information may be collected on our Website, how we use this information, and under what circumstances we may disclose the information to third parties. This Privacy Policy applies only to information we collect through the Website and does not apply to our collection of information from other sources.</p>
        <p>This Privacy Policy, together with the Terms and conditions posted on our Website, set forth the general rules and policies governing your use of our Website. Depending on your activities when visiting our Website, you may be required to agree to additional terms and conditions.</p>
        <p><b>Website Visitors</b></p>
        <p>Like most website operators, Deni Hidayat collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. Deni Hidayat's purpose in collecting non-personally identifying information is to better understand how Deni Hidayat's visitors use its website. From time to time, Deni Hidayat may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.</p>
        <p>Deni Hidayat also collects potentially personally-identifying information like Internet Protocol (IP) addresses for logged in users and for users leaving comments on https://denihida1216.github.io blog posts. Deni Hidayat only discloses logged in user and commenter IP addresses under the same circumstances that it uses and discloses personally-identifying information as described below.</p>
        <p>Gathering of Personally-Identifying Information</p>
        <p>Certain visitors to Deni Hidayat's websites choose to interact with Deni Hidayat in ways that require Deni Hidayat to gather personally-identifying information. The amount and type of information that Deni Hidayat gathers depends on the nature of the interaction. For example, we ask visitors who sign up for a blog at https://denihida1216.github.io to provide a username and email address.</p>
        <p><b>Security</b></p>
        <p>The security of your Personal Information is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.</p>
        <p><b>Advertisements</b></p>
        <p>Ads appearing on our website may be delivered to users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This Privacy Policy covers the use of cookies by Deni Hidayat and does not cover the use of cookies by any advertisers.</p>
        <p><b>Links To External Sites</b></p>
        <p>Our Service may contain links to external sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy and terms and conditions of every site you visit.</p>
        <p>We have no control over, and assume no responsibility for the content, privacy policies or practices of any third party sites, products or services.</p>
        <p><b>Https://denihida1216.github.io uses Google AdWords for remarketing</b></p>
        <p>Https://denihida1216.github.io uses the remarketing services to advertise on third party websites (including Google) to previous visitors to our site. It could mean that we advertise to previous visitors who haven't completed a task on our site, for example using the contact form to make an enquiry. This could be in the form of an advertisement on the Google search results page, or a site in the Google Display Network. Third-party vendors, including Google, use cookies to serve ads based on someone's past visits. Of course, any data collected will be used in accordance with our own privacy policy and Google's privacy policy.</p>
        <p>You can set preferences for how Google advertises to you using the Google Ad Preferences page, and if you want to you can opt out of interest-based advertising entirely by cookie settings or permanently using a browser plugin.</p>
        <p><b>Protection of Certain Personally-Identifying Information</b></p>
        <p>Deni Hidayat discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on Deni Hidayat's behalf or to provide services available at Deni Hidayat's website, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using Deni Hidayat's website, you consent to the transfer of such information to them. Deni Hidayat will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, Deni Hidayat discloses potentially personally-identifying and personally-identifying information only in response to a subpoena, court order or other governmental request, or when Deni Hidayat believes in good faith that disclosure is reasonably necessary to protect the property or rights of Deni Hidayat, third parties or the public at large.</p>
        <p>If you are a registered user of https://denihida1216.github.io and have supplied your email address, Deni Hidayat may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what's going on with Deni Hidayat and our products. We primarily use our blog to communicate this type of information, so we expect to keep this type of email to a minimum. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. Deni Hidayat takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</p>
        <p><b>Aggregated Statistics</b></p>
        <p>Deni Hidayat may collect statistics about the behavior of visitors to its website. Deni Hidayat may display this information publicly or provide it to others. However, Deni Hidayat does not disclose your personally-identifying information.</p>
        <p><b>Cookies</b></p>
        <p>To enrich and perfect your online experience, Deni Hidayat uses "Cookies", similar technologies and services provided by others to display personalized content, appropriate advertising and store your preferences on your computer.</p>
        <p>A cookie is a string of information that a website stores on a visitor's computer, and that the visitor's browser provides to the website each time the visitor returns. Deni Hidayat uses cookies to help Deni Hidayat identify and track visitors, their usage of https://denihida1216.github.io, and their website access preferences. Deni Hidayat visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using Deni Hidayat's websites, with the drawback that certain features of Deni Hidayat's websites may not function properly without the aid of cookies.</p>
        <p>By continuing to navigate our website without changing your cookie settings, you hereby acknowledge and agree to Deni Hidayat's use of cookies.</p>
        <p><b>Privacy Policy Changes</b></p>
        <p>Although most changes are likely to be minor, Deni Hidayat may change its Privacy Policy from time to time, and in Deni Hidayat's sole discretion. Deni Hidayat encourages visitors to frequently check this page for any changes to its Privacy Policy. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.</p>
        <p><b>Credit & Contact Information</b></p>
        <p>This privacy policy was created at <a href="#privacy-policy" title="Privacy policy" target="_blank">denihida1216.github.io</a>. If you have any questions about this Privacy Policy, please contact us via <a href="mailto:denihida1216@gmail.com">email</a> or <a href="tel:085721661555">phone</a>.</p>
      </div>
    );
  }
}

export default PrivacyPolicy;